# Generated by Django 3.0.8 on 2020-07-02 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='img',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='name',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='price',
        ),
    ]
